//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esoft_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealSet
    {
        public int id { get; set; }
        public int idSupply { get; set; }
        public int idDemand { get; set; }
    
        public virtual DemandSet DemandSet { get; set; }
        public virtual SupplySet SupplySet { get; set; }
    }
}
